### ISSUE TITLE
Figure out this weird crash

### ISSUE THREAD

**Issue by Trinsdar** [Reforged-Mods/Cinderscapes-Reforged#1]
https://gist.github.com/Trinsdar/a73f64ad2e0b82a12bd94c1d290777b7
Edit: seems the dependecies have nothing to do with it, at least as far as I can see, as removing them does not stop the crash

**Comment by PhweeDev** [comment]
I have a similar issue. either one of or all three of the mods are causing Cinderscapes Reforged to not start up. Even on its' own. and with both dev versions.
