### ISSUE TITLE
[1.19.2] Mod encounters an error during the common_setup phase

### ISSUE THREAD

**Issue by CrystalZink** [Reforged-Mods/Cinderscapes-Reforged#11]
Booted up a fresh 1.19.2 instance with only this mod just to make sure it wasnt something with my modpack, heres the log
Dependencies don't seem to be updated to 1.19.2 either, so I'm not sure if those are required anymore, if I missed something feel free to yell at me

[latest.log](https://github.com/user-attachments/files/17019786/latest.log)

**Comment by CrystalZink** [comment]
okay yeah wait nevermind the library is updated on modrinth but not curseforge, good reminder i guess

**Comment by Trinsdar** [comment]
no this is a bug, the dependency was supposed to be included inside the jar but was not, just uploaded a fix.
