### ISSUE TITLE
Game cannot get past modloading

### ISSUE THREAD

**Issue by PhweeDev** [Reforged-Mods/Cinderscapes-Reforged#2]
Hello,

I assume the project and its' dependents are not finished yet.  However here's an issue I've found.

Mods used:
NEBI 1.0.1
Terraform 1.0.2
Cinderscapes Reforged 1.0.0

Here's a few logs to maybe help you.
[latest.log](https://github.com/Reforged-Mods/Cinderscapes-Reforged/files/7122599/latest.log)
[debug.log](https://github.com/Reforged-Mods/Cinderscapes-Reforged/files/7122600/debug.log)

**Comment by Trinsdar** [comment]
First of all,  seems your still using the old nebi version.
Try downloading everything from modrinth(curseforge still hasn't approved them yet and won't till at least Thursday cause Israel holidays): https://modrinth.com/mod/terrestria-reforged.
edit: now that I'm at my computer, and was able to actually read the log, this issue definetlky looks like something I already fixed, please try updating everything to what's on modrinth, then try again
