### ISSUE TITLE
[1.18.2] Crash on startup

### ISSUE THREAD

**Issue by aking4125** [Reforged-Mods/Cinderscapes-Reforged#5]
**Description of the Bug**

Hello,
Upon launch, the game crashes with this report: https://pastebin.com/cAxn9t1S

Removing this mod allows the game to load normally. Any ideas?

**To Reproduce**

1. Load mods into pack
2. Start pack
3. Crash

**Expected behavior**
Not to crash and load normally?

**Logs & Environment**
[debug.log](https://github.com/Reforged-Mods/Cinderscapes-Reforged/files/8884474/debug.log)
[latest.log](https://github.com/Reforged-Mods/Cinderscapes-Reforged/files/8884475/latest.log)

**Additional context**
No crash report is created and the logs doesn't actually report the error shown at the end. That was copied directly from MultiMC. Basically the game just stops loading any further.

Forge 40.1.51 1.18.2

**Comment by Jukabofy** [comment]
Can confirm this too
