### ISSUE TITLE
[1.18.2] Luminous Grove not generating correctly.

### ISSUE THREAD

**Issue by Reshy** [Reforged-Mods/Cinderscapes-Reforged#8]
Version:  cinderscapes-forge-2.0.5.jar
Luminous Groves aren't generating correctly, the Umbral Nylium cannot have plants placed on it and seems to be missing all block tags to it.  

Lack of tags:
![2023-07-21_22 35 46](https://github.com/Reforged-Mods/Cinderscapes-Reforged/assets/2096384/a1d43114-6478-4677-aa61-694c613b6af7)

Compared to vanilla Nylium:
![2023-07-21_22 35 48](https://github.com/Reforged-Mods/Cinderscapes-Reforged/assets/2096384/31b56d75-272a-4c23-9b5d-a0f0e08629a8)

Additionally, most of the Luminous Grove is bare, lacking any Umbral Nylium and few plants:
![2023-07-21_22 13 22](https://github.com/Reforged-Mods/Cinderscapes-Reforged/assets/2096384/13d4e851-e4ef-4351-a2e3-7ff739f7d09e)
Modlist:
![image](https://github.com/Reforged-Mods/Cinderscapes-Reforged/assets/2096384/69758d53-e40f-4d59-8ef4-734c5887ca50)

**Comment by Trinsdar** [comment]
should be fixed now, if the issue was block tags and other data
